# Generated by Django 5.0.7 on 2024-07-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('student', 'Student'), ('staff', 'Staff'), ('security', 'Security'), ('maintenance', 'Maintenance')], max_length=15),
        ),
    ]
